import Head from "next/head";
import Layout from "../src/components/Layout";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div className="max-w-[1400px] mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="flex pt-[60px] md:pt-[75px] pb-[75px] gap-[35px] flex-col md:flex-row justify-between">
          <div className="">
            <div className="max-w-[500px]">
              <h1 className="font-semibold text-4xl sm:text-6xl lg:text-7xl mb-4">
                Discover <br /> Most Suitable <br /> Property
              </h1>
              <p className="mb-4">
                Find a variety of properties that suit you very easily, forget
                all difficulties in finding a residence for you
              </p>
            </div>
            <div className="flex mb-4 space-x-7">
              <div className="font-bold text-[25px]">
                9K <span>+</span>
                <div className="text-[13px] font-normal">
                  Premium <br /> Product
                </div>
              </div>

              <div className="font-bold text-[25px]">
                2K <span>+</span>
                <div className="text-[13px] font-normal">
                  Happy <br /> Customer
                </div>
              </div>

              <div className="font-bold text-[25px]">
                28K <span>+</span>
                <div className="text-[13px] font-normal">
                  Awards <br /> Winning
                </div>
              </div>
            </div>
          </div>
          <div className=" overflow-hidden max-h-[500px]">
            <img
              src="./home.png"
              alt="home"
              className="max-w-[800px] max-h-[800px] object-cover object-center"
            />
          </div>
        </section>
        <section className="pb-5">
          <div className="rounded-[20px] bg-zinc-500 py-9">
            <div className="text-center py-5 px-3 lg-px-10">
              <h2 className="text-3xl md:text-5xl font-semibold mb-3">
                Get started with Homes
              </h2>
              <p className="mb-9">
                We always ready to help by providing the best service for you.
              </p>
              <Link
                href="/search"
                className="p-4 bg-zinc-300 rounded-md font-medium ring ring-zinc-400 mt-8"
              >
                Get Started
              </Link>
            </div>
          </div>
        </section>
      </Layout>
    </div>
  );
}
